#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(Feat|Fix|Docs|Style|Refactor|Test|Chore|Design|Comment|Rename|Remove|!BREAKING CHANGE|!HOTFIX):.*$"

if ! [[ $message =~ $requiredPattern ]];
then
  echo "=========================================================================="
  echo "🚨 커밋 메시지 오류"
  echo "=========================================================================="
  echo "== 커밋 메시지 형식 => [헤더]: [어떤 작업을 왜 했는지]"
  echo "== 허용된 헤더 목록"
  echo "== 기능(Feat), 버그 수정(Fix), 문서(Docs), 스타일(Style), 리팩터(Refactor),"
  echo "== 테스트(Test), 작업 환경(Chore), 디자인(Design), 주석(Comment),"
  echo "== 파일명 변경(Rename), 파일 삭제(Remove), 🚨 변경사항(BREAKING CHANGE), 긴급 수정(HOTFIX)"
  echo "=========================================================================="
  echo "== 입력한 커밋 메시지 =>" $message 
  echo "== 자세한 사항은 .husky/commit-msg 또는 GUIDE.md를 참고하세요."
  echo "=========================================================================="
  exit 1
else
  echo "=========================================================================="
  echo "✅ 커밋이 정상적으로 생성되었습니다!"
  echo "=========================================================================="
fi